const execa = require('execa');

test('--help', async () => {
  const result = await execa.node('./cli.js', ['--help']);
  expect(result.exitCode).toBe(0);
  expect(result.stdout).toMatchInlineSnapshot(`
"
  Verify that a command generates files which match existing files on disk

  Verify that a command generates files which match existing files on disk.
  Files matching the path/glob specified by '-p' will be copied with a '.tmp' suffix, then the
  command will be executed, and newly-generated files will be compared with the existing '.tmp'
  files. If a diff is found, then diff-verify will exit with a status code of 1.

  Usage
    $ diff-verify -p <path|glob> [--dry-run] -- <command> [...args]

  Options
    --dry-run   Skip copying, emitting, diffing, and deleting files on disk. Only log operations
                which would be done.
    --path, -p  A path or glob specifying the files expected to be generated by the command.

  Examples
    $ diff-verify -p apps/bot-studio-web/graphql-types.ts -- node_modules/.bin/graphql-codegen --config apps/bot-studio-web/codegen.yml

    $ diff-verify -p apps/admin-web/locales -- pnpm run nx -- run admin-web:linguiExtract
"
`);
});

test('simple', async () => {
  const result = await execa.node('./cli.js', ['-p', 'generated.txt', '--', 'node', 'generate.js']);
  expect(result.exitCode).toBe(0);
  console.log(result);
});
